services:
  - type: web
    name: ficha-dentcool
    runtime: static
    rootDir: dentcool-project
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
