export const DEFAULT_SUPPLY_CATEGORIES = [
  'Desechables',
  'Bioseguridad',
  'Profilaxis',
  'Blanqueamiento',
  'Restauracion',
  'Anestesia',
  'Instrumental reutilizable',
  'Equipos amortizables',
  'Esterilizacion',
  'Oficina',
  'Otros',
];

export const DEFAULT_SUPPLY_UNITS = [
  'unidad',
  'par',
  'caja',
  'pack',
  'ml',
  'mg',
  'g',
  'dosis',
  'rollo',
  'uso',
  'paciente estimado',
  'semana',
  'jornada',
];

export const DEFAULT_SUPPLY_SUPPLIERS = [
  {
    id: 'prov_dental_001',
    name: 'Proveedor Dental X',
    contactName: '',
    phone: '',
    email: '',
    address: '',
    website: '',
    notes: 'Proveedor base para insumos desechables y bioseguridad',
    active: true,
  },
];

export const DEFAULT_SUPPLY_CATALOG = [
  {
    id: 'sup_vaso_001',
    name: 'Vaso desechable',
    category: 'Desechables',
    itemType: 'consumable',
    unit: 'unidad',
    purchaseQuantity: 100,
    purchaseTotalCost: 3000,
    unitCost: 30,
    currentStock: 240,
    minimumStock: 30,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Uso transversal en evaluaciones y tratamientos',
  },
  {
    id: 'sup_guante_001',
    name: 'Guantes',
    category: 'Bioseguridad',
    itemType: 'consumable',
    unit: 'par',
    purchaseQuantity: 100,
    purchaseTotalCost: 12000,
    unitCost: 120,
    currentStock: 120,
    minimumStock: 20,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Par por atencion clinica',
  },
  {
    id: 'sup_mascarilla_001',
    name: 'Mascarilla',
    category: 'Bioseguridad',
    itemType: 'consumable',
    unit: 'unidad',
    purchaseQuantity: 50,
    purchaseTotalCost: 5000,
    unitCost: 100,
    currentStock: 100,
    minimumStock: 20,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Bioseguridad basica por paciente',
  },
  {
    id: 'sup_pechera_001',
    name: 'Pechera desechable',
    category: 'Bioseguridad',
    itemType: 'consumable',
    unit: 'unidad',
    purchaseQuantity: 50,
    purchaseTotalCost: 7500,
    unitCost: 150,
    currentStock: 60,
    minimumStock: 10,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Proteccion del paciente y del box',
  },
  {
    id: 'sup_eyector_001',
    name: 'Eyector',
    category: 'Desechables',
    itemType: 'consumable',
    unit: 'unidad',
    purchaseQuantity: 100,
    purchaseTotalCost: 8000,
    unitCost: 80,
    currentStock: 180,
    minimumStock: 30,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Uso transversal en limpieza y evaluacion',
  },
  {
    id: 'sup_gasa_001',
    name: 'Gasa',
    category: 'Desechables',
    itemType: 'consumable',
    unit: 'unidad',
    purchaseQuantity: 500,
    purchaseTotalCost: 20000,
    unitCost: 40,
    currentStock: 500,
    minimumStock: 50,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 2,
    active: true,
    notes: 'Consumible clinico de apoyo',
  },
  {
    id: 'sup_fluor_001',
    name: 'Fluor',
    category: 'Profilaxis',
    itemType: 'medicine',
    unit: 'dosis',
    purchaseQuantity: 20,
    purchaseTotalCost: 24000,
    unitCost: 1200,
    currentStock: 20,
    minimumStock: 4,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Aplicacion preventiva',
  },
  {
    id: 'sup_pasta_profilactica_001',
    name: 'Pasta profilactica',
    category: 'Profilaxis',
    itemType: 'consumable',
    unit: 'dosis',
    purchaseQuantity: 20,
    purchaseTotalCost: 30000,
    unitCost: 1500,
    currentStock: 18,
    minimumStock: 3,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Uso en limpiezas',
  },
  {
    id: 'sup_blanqueador_001',
    name: 'Gel blanqueador',
    category: 'Blanqueamiento',
    itemType: 'medicine',
    unit: 'dosis',
    purchaseQuantity: 10,
    purchaseTotalCost: 70000,
    unitCost: 7000,
    currentStock: 10,
    minimumStock: 2,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Material de blanqueamiento en consulta',
  },
  {
    id: 'sup_resina_001',
    name: 'Resina compuesta',
    category: 'Restauracion',
    itemType: 'consumable',
    unit: 'uso',
    purchaseQuantity: 10,
    purchaseTotalCost: 45000,
    unitCost: 4500,
    currentStock: 10,
    minimumStock: 2,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Material de restauracion directa',
  },
  {
    id: 'med_anestesia_001',
    name: 'Anestesia carpule',
    category: 'Anestesia',
    itemType: 'medicine',
    unit: 'dosis',
    purchaseQuantity: 50,
    purchaseTotalCost: 50000,
    unitCost: 1000,
    currentStock: 50,
    minimumStock: 10,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Control de dolor y confort',
  },
  {
    id: 'eq_aeropulidor_001',
    name: 'Aeropulidor',
    category: 'Equipos amortizables',
    itemType: 'equipment',
    unit: 'uso',
    purchaseQuantity: 60,
    purchaseTotalCost: 30000,
    unitCost: 500,
    currentStock: 1,
    minimumStock: 0,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Costo amortizado por uso',
  },
  {
    id: 'pack_examen_001',
    name: 'Pack examen esterilizado',
    category: 'Esterilizacion',
    itemType: 'pack',
    unit: 'uso',
    purchaseQuantity: 400,
    purchaseTotalCost: 520000,
    unitCost: 1300,
    currentStock: 40,
    minimumStock: 6,
    supplierId: 'prov_dental_001',
    defaultUsePerPatient: 1,
    active: true,
    notes: 'Amortizacion + esterilizacion por uso',
  },
];

export const DEFAULT_SUPPLY_RECIPES = [
  {
    id: 'recipe_evaluacion',
    treatmentId: 'evaluacion',
    name: 'Lista base Evaluacion',
    active: true,
    includesBaseDisposablePack: true,
    includesExamPack: true,
    items: [
      { itemId: 'sup_vaso_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_guante_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_mascarilla_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_eyector_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'pack_examen_001', quantity: 1, editableAtPatientLevel: true },
    ],
    notes: 'Evaluacion base con packs transversales',
  },
  {
    id: 'recipe_limpieza_standard',
    treatmentId: 'limpieza-standard',
    name: 'Lista base Limpieza standard',
    active: true,
    includesBaseDisposablePack: true,
    includesExamPack: true,
    items: [
      { itemId: 'sup_vaso_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_guante_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_mascarilla_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_eyector_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_gasa_001', quantity: 2, editableAtPatientLevel: true },
      { itemId: 'sup_pasta_profilactica_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'pack_examen_001', quantity: 1, editableAtPatientLevel: true },
    ],
    notes: 'Limpieza con profilaxis y pack esterilizado',
  },
  {
    id: 'recipe_limpieza_vip',
    treatmentId: 'limpieza-vip',
    name: 'Lista base Limpieza VIP',
    active: true,
    includesBaseDisposablePack: true,
    includesExamPack: true,
    items: [
      { itemId: 'sup_vaso_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_guante_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_mascarilla_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_eyector_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_gasa_001', quantity: 2, editableAtPatientLevel: true },
      { itemId: 'sup_fluor_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_pasta_profilactica_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'eq_aeropulidor_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'pack_examen_001', quantity: 1, editableAtPatientLevel: true },
    ],
    notes: 'Limpieza premium con aeropulidor y fluor',
  },
  {
    id: 'recipe_blanqueamiento_consulta',
    treatmentId: 'blanqueamiento-consulta',
    name: 'Lista base Blanqueamiento en consulta',
    active: true,
    includesBaseDisposablePack: true,
    includesExamPack: true,
    items: [
      { itemId: 'sup_vaso_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_guante_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_mascarilla_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_eyector_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_blanqueador_001', quantity: 2, editableAtPatientLevel: true },
      { itemId: 'pack_examen_001', quantity: 1, editableAtPatientLevel: true },
    ],
    notes: 'Blanqueamiento en silla con pack base',
  },
  {
    id: 'recipe_restauracion_simple',
    treatmentId: 'restauracion-simple',
    name: 'Lista base Restauracion simple',
    active: true,
    includesBaseDisposablePack: true,
    includesExamPack: true,
    items: [
      { itemId: 'sup_vaso_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_guante_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_mascarilla_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_eyector_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_gasa_001', quantity: 2, editableAtPatientLevel: true },
      { itemId: 'med_anestesia_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_resina_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'pack_examen_001', quantity: 1, editableAtPatientLevel: true },
    ],
    notes: 'Restauracion directa con anestesia y resina',
  },
  {
    id: 'recipe_sellantes',
    treatmentId: 'sellantes',
    name: 'Lista base Sellantes',
    active: true,
    includesBaseDisposablePack: true,
    includesExamPack: true,
    items: [
      { itemId: 'sup_vaso_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_guante_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_mascarilla_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_eyector_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'sup_gasa_001', quantity: 1, editableAtPatientLevel: true },
      { itemId: 'pack_examen_001', quantity: 1, editableAtPatientLevel: true },
    ],
    notes: 'Preventivo de bajo ticket',
  },
];
